### ISSUE TITLE
Allow customization of install executable (pip)

### ISSUE THREAD

**Issue by asottile** [spotify/dh-virtualenv#160] opened 2016-06-21 19:29 UTC
We'd love to be able to leverage these tools when building dh-virtualenv packages:
- [pip-faster](https://github.com/Yelp/venv-update)
- [pip-custom-platform](https://github.com/asottile/pip-custom-platform)

We currently have no way of doing so with dh-virtualenv.

Ideally (?) we could do something like this:

```Makefile
override_dh_virtualenv:
	dh_virtualenv --preinstall venv-update==1.1 --pip-tool 'pip-faster --upgrade'
```

CC @chriskuehl

**Comment by nailor** [comment] 2016-08-02 07:48
Hi,

this is a duplicate of #143. While supporting an arbitrary executable instead of `pip` would not be too hard, just adding a flag, there are multiple issues:

- Some flags might not work out of the box. What if the custom pip replacement breaks on `--index-url` flag?
- The example highlights another issue: We would need to run the command through `shlex` or similar tool to split it in order to not shell bomb your build server

There's probably more issues which would emerge, thus I'm not in favour of adding this particular feature

**Comment by asottile** [comment] 2016-08-02 17:59
I don't see these as issues for the following reason:

> What if the custom pip replacement breaks on --index-url flag?

Then that's user error, they'll see an error message and that's fine --  they'll fix it.  Same for if someone specified unsupported arguments against unsupported versions of pip.

> We would need to run the command through shlex or similar tool to split it in order to not shell bomb your build server

That's easy, there's `shlex.shlex` in the python stdlib

> There's probably more issues which would emerge

I don't think "there'll probably be other problems" is actually a problem statement.

**Comment by asottile** [comment] 2016-08-02 18:06
I'd even be ok without the shlex, `--pip-tool pip-custom-platform` would solve many of my usecases as-is

**Comment by nailor** [comment] 2016-08-03 09:12
And aliasing as described in #143 won't work?

**Comment by nailor** [comment] 2016-08-03 09:43
While I know the "other problems" argument is stupid indeed, at least one other popped into the mind: when should the custom pip command be installed? How should it interact with the flow in general?

Since the tool at the moment relies quite heavily on the fact that the pip is available upon creation of the virtualenv, it would need to be able to figure out the correct point of running the custom pip command.

From top of my head quick potential solutions to the custom pip command:

- _Install a virtualenv with the custom pip command_
  Not sure if this is feasible in any way?

- _Use default virtualenv, but install custom pip command in it, identified by `--pip-tool` flag._
  What if the package name differs from the command you want to run? Another flag for pip executable?

- _Use `--preinstall` flag to make sure the custom pip command is installed with `--preinstall``_
  What about other packages defined with `--preinstall`? Should they be installed with custom pip or normal? Would the order dictate? Can we guarantee the order? Will it be confusing?

None of these is in any way bullet proof solution, so unless there's a neat solution that solves the ambivalence of the custom pip command, I'm reluctant to have it as a feature.

**Comment by asottile** [comment] 2016-08-03 13:41
The spec I hinted at in the description is that all pre install packages are installed using vanilla pip after the virtualenv is created with a single invocation of pip install.  Points one and two above are not applicable. The pip tool is only useful for installing the target package and its requirements. 

The solution in #143 is not possible as far as I can tell. Exporting a shell alias won't help unless type using a shell and the shell that exported the alias.  And getting a custom pip executable on the path named pip would have to involve some sort of destruction of the pip executable in the virtualenv which would probably need the `--preinstall` command hinted at in the description.  And even then it would be a huge huge hack.

**Comment by nailor** [comment] 2016-08-03 15:01
But it would still be weird if `--preinstall` would install packages with normal pip. What if you need to preinstall something crazy heavy (numpy?) and would like to get the speedup there.

What I'm arguing that all these create weird corner cases that would need to be extensively documented (and people would still trip on as no-one reads all of the docs)

**Comment by asottile** [comment] 2016-08-03 16:47
There's not much at all to document here at all, it'd be a very simple premise:

`--preinstall package1 --preinstall package2` - Installs package1 and package2 via `pip install package1 package2` directly after virtualenv creation.
`--pip-tool pip-tool-x` - When installing the dh-virtualenv target (setup.py + requirements.txt) invokes `pip-tool-x install ...` instead of `pip install ...`

I've already implemented something similar in several other tools, it's very straightforward I promise :) https://github.com/asottile/scratch/blob/b8f25d22675a4fecfd7e78c029cd8bcd07db12ec/python/check-all-wheels.py#L34-L35

I also don't think numpy problem is any different from the status quo -- it's equally unsupported as it is now.

**Comment by nailor** [comment] 2016-08-04 08:10
Hmm, guess it could be underlined in a nice way in documentation, as long as the cut-off point (pip to custom pip) is done in a nice way.

Do you think you could do a PR for this? You seem to have a valid enough reasons to do this :)

**Comment by asottile** [comment] 2016-08-04 13:58
Yep, I can take a stab at this.  About to go on vacation but I'll probably be able to get to it when I'm back :)

**Comment by bukzor** [comment] 2016-08-10 20:16
Both this and it's duplicate ticket are closed. Shouldn't one be open if we're contemplating merging a patch for this?

**Comment by nailor** [comment] 2016-09-01 16:26
Good point (sorry for a slow response, was on vacation here too). This is now reopened :)

**Closed** 2016-09-15 19:39 UTC
Labels: duplicate
