### ISSUE TITLE
python: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by dennybaa** [spotify/dh-virtualenv#124] opened 2015-12-04 15:02 UTC
Hello,

Packaged python scripts get shebang interpreter `#!python`.

Invocation like this:
```make
override_dh_virtualenv:
	dh_virtualenv --extra-pip-arg '--find-links=$(WHEELDIR)' \
								--no-test
```

**Comment by nailor** [comment] 2015-12-04 15:19
Thanks for reporting the issue!

Does your project happen to be available open source or can you possibly reproduce it somehow? What you have added here should not cause the Python to get empty.

One problem that I can think of: Are you sure the `WHEELDIR` is set and gets replaced correctly?

**Comment by dennybaa** [comment] 2015-12-04 15:47
Hi, the project is opensource.
Yeah it might difficult to try, however, here's the input) I don't know there's something which break dh_virtualenv, because it was working before(((

1. Unfortunately I don't know the exact version of `dh_virtualenv`, it should be quite recent however. Due to is bundled in the way here https://github.com/StackStorm/st2-dockerfiles/blob/master/packagingenv/wheezy/Dockerfile#L19-L25.
2. You can grab the project here https://github.com/dennybaa/st2-packages/tree/dh-testing
3. Running build: `docker-compose run wheezy`
4. You'll get two containers which have the required input: `st2packages_wheezybuild_1` and `st2packages_wheezytest_1`.
  Further you can exec into container: `docker exec -it st2packages_wheezybuild_1 bash`

Locations:
  * Source is located on **wheezybuild** in directory `/tmp/st2-xxxxxxxxx`
  * Services are installed on to **wheezytest**, you can simply `cat /usr/share/python/st2api/bin/st2api` and you'll get the wrong shebang :(

Thank you

**Comment by dennybaa** [comment] 2015-12-07 10:17
@nailor Hi, there!

I've located the issue, it's not caused by `dh-virtualenv` itself)
```
================================
debian/st2common/usr/share/python/st2common/bin/waitress-serve
s|^#!.*bin/\(env \)\?python|#!/usr/share/python/st2common/bin/python|
================================
debian/st2common/usr/share/python/st2common/bin/easy_install
s|^#!.*bin/\(env \)\?python|#!/usr/share/python/st2common/bin/python|
================================
```

Something definitely havocs shebang to look like in the second case, that's why regex fails of course. So far this is all input that I have. Going to dig into the problem with my project...

**Comment by dennybaa** [comment] 2015-12-07 11:52
I've made some digging, and found that scripts originally containing shebang `#!python` are not fixed with `fix_shebang` methods.
Now it's left to find out why these scripts originally go with such a shebang )

**Comment by nailor** [comment] 2015-12-07 12:00
Yeah, looks like the original shebang is wrong. I'm closing this, let me know if this tracks back to dh-virtualenv somehow by re-opening the issue!

**Closed by nailor** 2015-12-07 12:00 UTC

**Comment by dennybaa** [comment] 2015-12-07 12:02
@nailor  Yeap. But might you can have any clues just for the case, why it might usually happen?

**Comment by dennybaa** [comment] 2015-12-07 12:04
I mean, it's setup.py with setuptools are responsible, for the substitution. I can't get an idea why it goes there. Of course in our source is smth like `#!/usr/bin/env python2.7` is used...

**Comment by nailor** [comment] 2015-12-07 12:07
I have not seen that happening before, unfortunately. Would also be weird if that would be caused by some surrounding infra, like docker

**Comment by dennybaa** [comment] 2015-12-07 12:42
just FYI @nailor . I've further located the issue. `fix_shebang` and dh_virtualenv are working as expected.
However what is strange, is that it happens on `deploy.install_package()` phase. 
First I interrupted execution after installing deps, `xxx/python xxx/pip install -r requirements.txt` and found that shebangs of scripts point to normal temporary xxx/bin/python as it should be.
But `install_package()` phase ruins scripts of package itself (( Namely that code which invokes `xxx/python xxx/pip install .` results in scripts with this strange shebang `#!python`

That's kinda ultra strange, so I thought you might have an idea about it.
Thank you!

**Comment by nailor** [comment] 2015-12-07 12:45
@dennybaa Weird indeed. And I'm guessing the invocation is still the same, i.e. no `--python` defined? That could be the only way I can think of this could go bananas. Unless of course something in the `pip install` phase goes and writes in bogus shebangs (packages detect they are in virtualenv and do some magic? Super weird.)

**Comment by dennybaa** [comment] 2015-12-07 13:01
Just to be more precise. I've shut down the execution with sys.exit(1), and printed command which `dh_virtualenv` is going to run:

```
['/tmp/st2-20151207-7-11sbosp/st2common/debian/st2common/usr/share/python/st2common/bin/python', '/tmp/st2-20151207-7-11sbosp/st2common/debian/st2common/usr/share/python/st2common/bin/pip', 'install', '--log=/tmp/tmpzZduZQ', '--find-links=/tmp/wheelhouse', '.']
```

And i've manually run it in the shell (no virtualenv is exported or anything). Just like this:

`/tmp/st2-20151207-7-11sbosp/st2common/debian/st2common/usr/share/python/st2common/bin/python /tmp/st2-20151207-7-11sbosp/st2common/debian/st2common/usr/share/python/st2common/bin/pip install --find-links=/tmp/wheelhouse .`

And 
```
head -n1 debian/st2common/usr/share/python/st2common/bin/st2-bootstrap-rmq 
#!python
```

Actually I'm caught, it's beyond my understanding of pip... Either I should fork `dh_virtualenv` and make it work with a new regex for bogus shebang. Personally I've got no doubts it works :)
Or digging into nowhere to find where this wilderness comes from(

**Comment by nailor** [comment] 2015-12-07 13:10
Well the shebang modification is [a separate step](https://github.com/spotify/dh-virtualenv/blob/master/dh_virtualenv/deployment.py#L174), it is not related to the pip-installing of that code.

Is the pip using the wheels for installing? If that's the case, maybe the wheels have a wrong shebang in them and should be regenerated (if possible). You can extract the file just by unzipping them. Here's more info about the actual file format: https://www.python.org/dev/peps/pep-0427/#file-format

**Comment by dennybaa** [comment] 2015-12-07 13:26
Yes it does. Thank you very much for being around and your help Jyrki! You've helped to narrow down the possible scope, this is exactly caused by pre-generated wheels.

**Comment by jhermann** [comment] 2015-12-07 14:37
Your basic problem is you write your bin/ wrappers yourself, instead of using setuptools console entry points (which generates shims with the correct bang paths).

**Comment by dennybaa** [comment] 2015-12-07 16:39
@jhermann Thank you for the comment, yeah not all of our scripts are generated using setuptools entry points( I'll try to move the team in this direction when it'll be possible.

**Comment by dennybaa** [comment] 2015-12-07 17:30
@nailor I'd like to re-open this) It seems like if we install from wheels, we must expect shebang  `#!python`. 
There's even a bug when not proper shebang sneak into. So what do you think of validity of `#!python shebang` ?

**Comment by dennybaa** [comment] 2015-12-07 17:46
@jhermann I've checked, and and confirm that we are using `scripts` entry-point which is also valid along with console. wheeled packages contain "#!python" shebang line, here's info https://docs.python.org/2/distutils/setupscript.html#installing-scripts

**Comment by jhermann** [comment] 2015-12-08 11:32
The exact wording is ‹first line of the script starts with #! and **contains** the word “python”› (emphasis mine). So possibly the rewriting code should be more lenient regarding when the rewrite is actually triggered,

**Comment by dennybaa** [comment] 2015-12-08 15:19
@jhermann Do I get you right?. I'm also not saying about the place where rewrite is triggered. I'm saying about how it acts, **fix_shebangs** takes in account only `.*/bin/python` and `.*/bin/env python` which is clearly more strict than https://docs.python.org/3.3/distutils/setupscript.html#installing-scripts define(

I've checked wheels, after unzipping a wheel there's the scripts directory which contains scripts with shebang exactly == `#!python`. For some reason `pip install --find-links=/some/wheeldir .` doesn't change interpreter to look like anything **fix_shebangs** wants, thus the rewrite doesn't happen and scripts are left with shebang `#!python`.

**Comment by evilaliv3** [comment] 2016-01-11 00:16
@nailor  i'm getting the same error of @dennybaa python is not found.

i'm packaging GlobaLeaks and Tor2web using dh-virtualenv

i  think that the issue of @dennybaa (like for me) is that i'm building on a machine 64bits and the machine where i'm installing is a 32 bit so that the python binary and all the other binaries included in the virtual env cannot work because they are all 64bit

how do you generally manage with this condition? how to build a multiarchitectural virtualenv/package?

```bash
root@tor2web:~# ls /usr/share/python/tor2web/bin/ -al
total 3376
drwxr-xr-x 2 root root    4096 Jan 10 23:59 .
drwxr-xr-x 6 root root    4096 Jan 10 23:51 ..
-rw-r--r-- 1 root root    2250 Jan 10 23:39 activate
-rw-r--r-- 1 root root    1306 Jan 10 23:39 activate.csh
-rw-r--r-- 1 root root    2519 Jan 10 23:39 activate.fish
-rw-r--r-- 1 root root    1129 Jan 10 23:39 activate_this.py
-rwxr-xr-x 1 root root     346 Jan 10 23:39 cftp
-rwxr-xr-x 1 root root     349 Jan 10 23:39 ckeygen
-rwxr-xr-x 1 root root     347 Jan 10 23:39 conch
-rwxr-xr-x 1 root root     754 Jan 10 23:39 cyclone
-rwxr-xr-x 1 root root     335 Jan 10 23:39 easy_install
-rwxr-xr-x 1 root root     253 Jan 10 23:39 easy_install-2.7
-rwxr-xr-x 1 root root     343 Jan 10 23:39 easy_install-3.4
-rwxr-xr-x 1 root root     346 Jan 10 23:39 lore
-rwxr-xr-x 1 root root     405 Jan 10 23:39 mailmail
-rwxr-xr-x 1 root root     307 Jan 10 23:39 manhole
-rwxr-xr-x 1 root root     225 Jan 10 23:39 pip
-rwxr-xr-x 1 root root     225 Jan 10 23:39 pip2
-rwxr-xr-x 1 root root     225 Jan 10 23:39 pip2.7
-rwxr-xr-x 1 root root     237 Jan 10 23:39 pyhtmlizer
-rwxr-xr-x 1 root root 3345416 Jan 10 23:39 python
lrwxrwxrwx 1 root root       6 Jan 10 23:39 python2 -> python
lrwxrwxrwx 1 root root       6 Jan 10 23:39 python2.7 -> python
-rwxr-xr-x 1 root root     257 Jan 10 23:39 tap2deb
-rwxr-xr-x 1 root root     345 Jan 10 23:39 tap2rpm
-rwxr-xr-x 1 root root     239 Jan 10 23:39 tapconvert
-rwxr-xr-x 1 root root     349 Jan 10 23:39 tkconch
-rwxr-xr-x 1 root root     199 Jan 10 23:39 tor2web
-rwxr-xr-x 1 root root     372 Jan 10 23:39 trial
-rwxr-xr-x 1 root root     289 Jan 10 23:39 twistd
```

you can see here that the installed packages has python elf but the python included in the package is a 64bit version not compatible with the 32bit system and if i simply run "python" i get command not found simply because the elf file is not compatible
```bash
ls /usr/share/python/tor2web/bin/python -al
-rwxr-xr-x 1 root root 3345416 Jan 10 23:39 /usr/share/python/tor2web/bin/python
```

```bash
file python
python: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=502c59409208bd0bf5acfa9c497107ec487e3bd6, stripped
```

```bash
/usr/share/python/tor2web/bin# ./python
-bash: ./python: No such file or directory
```

**Comment by evilaliv3** [comment] 2016-01-11 00:40
ok i got also this problem solved :)

Architecture: any  in debian/control

debuild -aarch for building different package i386 or amd64

**Comment by chance2021** [comment] 2022-12-16 20:16
In my case, the error shows in Github action and the root cause is the broken python symbolic link. As a workaround, I just simply re-create it during the process.
```
Error：
home/runner/work/_temp/810926a2-36c5-4488-ac84-6f3f57713147.sh: /home/runner/work/dataops/dataops/.venv/bin/pytest: /home/runner/work/dataops/dataops/.venv/bin/python: bad interpreter: No such file or directory

Root Cause:
/home/runner/work/dataops/dataops/.venv/bin/python: broken symbolic link to /opt/hostedtoolcache/Python/3.9.15/x64/bin/python3.9

Solution:
Add below scripts into wherever has broken link:
        PYTHON_PATH=$(which python3)
        source .venv/bin/activate
        PYTHON_BROKEN_PATH=$(dirname $(which pip))
        rm $PYTHON_BROKEN_PATH/python
        ln -s $PYTHON_PATH $PYTHON_BROKEN_PATH/python
        export PATH=$PATH:$(dirname $PYTHON_BROKEN_PATH)
```
