### ISSUE TITLE
Add support for a custom pip command

### ISSUE THREAD

**Issue by danpalmer** [spotify/dh-virtualenv#143] opened 2016-03-02 13:30 UTC
[pip-accel](https://github.com/paylogic/pip-accel) is a replacement for the `pip install` command that very aggressively caches in order to speed up installation of requirements for virtual environments.

Being able to use `pip-accel install ...` instead of `pip install ...` with `dh_virtualenv`, successive builds could be significantly faster.

This is a bit obscure, if this isn't appropriate I understand and I will try and workaround it somehow, however, I think `dh_virtualenv` and `pip-accel` could be really useful together for fast package builds. Thoughts?

**Comment by nailor** [comment] 2016-03-02 13:42
Modern versions of `pip` can actually cache the wheels built for installs, so you should be able to benefit from that. `pip-accel` could probably make the caching even better (though I'm not familiar with the product)

Supporting different caching solutions at `dh-virtualenv` directly is slightly problematic. Lots of  builds happen in 'funny' environments, like custom chroots or such, that don't necessarily guarantee that anything sticks between builds or is even accessible. That way using any tool that provides caching in the `dh-virtualenv` would be really hard to make an universal solution.

Solution we at Spotify use is to actually pre-create wheels in our pypi mirror for certain packages for the platform we use. Others have also abused the ccache of Debian sbuild to keep something cached between builds.

Since, as stated above adding, adding any universal solution to dh-virtualenv is kind of problematic, I'll close this issue.

**Closed by nailor** 2016-03-02 13:42 UTC

**Comment by danpalmer** [comment] 2016-03-02 13:50
Hi @nailor, thanks for the detailed response.

> Supporting different caching solutions at dh-virtualenv directly is slightly problematic. Lots of builds happen in 'funny' environments, like custom chroots or such, that don't necessarily guarantee that anything sticks between builds or is even accessible. That way using any tool that provides caching in the dh-virtualenv would be really hard to make an universal solution.

I'm not asking for any sort of custom caching _in `dh_virtualenv`_, I'm looking for a hook so that we can implement custom caching in our own build process. We currently build in a chroot, and are also looking at Docker, and both of these would allow us to persist a cache between builds.

> Solution we at Spotify use is to actually pre-create wheels in our pypi mirror for certain packages for the platform we use.

That sounds like a good solution, but also sounds like a fair bit of tooling is required (running a PyPI mirror, pulling down package updates, extending packages with wheel support, etc) that is a bit much for our size.

I'm not familiar with the internals of `dh_virtualenv`, but would it be possible to provide an `override_*` rule that would allow us to replace the `pip install` command with what we wanted?

**Comment by jhermann** [comment] 2016-03-02 13:57
One option is devpi and setting `PIP_INDEX_URL` (the shell env is the one thing easily transported across the package build chain). devpi is rather trivial to set up, even on your own workstation – esp. on Debian-type system, where incidentally a [dh-virtualenv packge](https://github.com/jhermann/devpi-enterprisey/tree/master/debianized-devpi) exists.

If you want to use pip-accel, a shell function mapping it to the name `pip` and `export -f` might actually work.

**Comment by einarf** [comment] 2016-03-02 14:03
I don't think allowing a custom pip command would make that much trouble?

**Comment by danpalmer** [comment] 2016-03-02 14:04
@jhermann Nice idea for how to force the use of `pip-accel`, I was thinking something along those lines. Could definitely work.

**Comment by nailor** [comment] 2016-03-03 09:55
While just having a custom pip command would not be a huge load of trouble, the problem is that nothing guarantees the custom pip command will work the same way as the regular pip command. That means that in order to support _any_ custom pip command, one might need to add a ton of other functionality to define custom installation flags etc. 

I'm more in favour of aliasing the pip like @jhermann proposed instead of us supporting it natively

**Comment by einarf** [comment] 2016-03-03 13:48
@nailor I see your point. Agreed. Having to alias pip makes the user responible of forwarding the parameters and removes a lot of potential complexity now and in the future.
