### ISSUE TITLE
TypeError when installing pip

### ISSUE THREAD

**Issue by ethanaward** [spotify/dh-virtualenv#169] opened 2016-09-07 23:12 UTC
### Description:
I've been trying to build a python package with dh_virtualenv. I've been able to get it to build properly on my personal system, but when trying to install on a clean system, it always fails with the same error. I've seen that error in shazow/urllib3#567, but the fix there doesn't seem to have worked for me.

### Logs:

```
dpkg-buildpackage: source package mycroft-core
dpkg-buildpackage: source version 0.7.14-1ppa1
dpkg-buildpackage: source distribution xenial
 dpkg-source --before-build mycroft-core-0.7.14
dpkg-buildpackage: host architecture i386
 fakeroot debian/rules clean
dh clean -S --buildsystem=dh_virtualenv --setuptools --python=python2.7 --no-test
   dh_testdir -O-S -O--buildsystem=dh_virtualenv -O--setuptools -O--python=python2.7 -O--no-test
   dh_auto_clean -O-S -O--buildsystem=dh_virtualenv -O--setuptools -O--python=python2.7 -O--no-test
   dh_clean -O-S -O--buildsystem=dh_virtualenv -O--setuptools -O--python=python2.7 -O--no-test
	rm -f debian/debhelper-build-stamp
	rm -f debian/mycroft-core.substvars
	rm -f debian/mycroft-core.*.debhelper
	rm -rf debian/mycroft-core/
	rm -rf debian/.debhelper/
	rm -f debian/*.debhelper.log
	rm -f debian/files
	find .  \( \( \
		\( -path .\*/.git -o -path .\*/.svn -o -path .\*/.bzr -o -path .\*/.hg -o -path .\*/CVS \) -prune -o -type f -a \
	        \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
		 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
		 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
		 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
		\) -exec rm -f {} + \) -o \
		\( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
	rm -f *-stamp
 debian/rules build-arch
dh build-arch -S --buildsystem=dh_virtualenv --setuptools --python=python2.7 --no-test
   dh_testdir -a -O-S -O--buildsystem=dh_virtualenv -O--setuptools -O--python=python2.7 -O--no-test
   dh_update_autotools_config -a -O-S -O--buildsystem=dh_virtualenv -O--setuptools -O--python=python2.7 -O--no-test
   dh_auto_configure -a -O-S -O--buildsystem=dh_virtualenv -O--setuptools -O--python=python2.7 -O--no-test
	mkdir -p build/usr/lib/mycroft-core
   dh_auto_build -a -O-S -O--buildsystem=dh_virtualenv -O--setuptools -O--python=python2.7 -O--no-test
	cd build
	virtualenv --always-copy --clear /«PKGBUILDDIR»/build/usr/lib/mycroft-core
Not deleting /«PKGBUILDDIR»/build/usr/lib/mycroft-core/bin
New python executable in /«PKGBUILDDIR»/build/usr/lib/mycroft-core/bin/python2
Also creating executable in /«PKGBUILDDIR»/build/usr/lib/mycroft-core/bin/python
Installing setuptools, pkg_resources, pip, wheel...
  Complete output from command /build/mycroft-core-...oft-core/bin/python2 - setuptools pkg_resources pip wheel:
  Collecting setuptools
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/req/req_set.py", line 512, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/req/req_install.py", line 273, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/index.py", line 442, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/index.py", line 400, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/index.py", line 545, in _get_pages
    page = self._get_page(location)
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/index.py", line 648, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/index.py", line 757, in get_page
    "Cache-Control": "max-age=600",
  File "/«PKGBUILDDIR»/build/usr/lib/mycroft-core/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/download.py", line 378, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/«PKGBUILDDIR»/build/usr/lib/mycroft-core/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/«PKGBUILDDIR»/build/usr/lib/mycroft-core/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/«PKGBUILDDIR»/build/usr/lib/mycroft-core/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/«PKGBUILDDIR»/build/usr/lib/mycroft-core/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/adapters.py", line 376, in send
Traceback (most recent call last):
    timeout=timeout
  File "/«PKGBUILDDIR»/build/usr/lib/mycroft-core/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 610, in urlopen
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    _stacktrace=sys.exc_info()[2])
  File "/«PKGBUILDDIR»/build/usr/lib/mycroft-core/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 228, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
----------------------------------------
...Installing setuptools, pkg_resources, pip, wheel...done.
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /build/mycroft-core-...oft-core/bin/python2 - setuptools pkg_resources pip wheel failed with error code 2
Running virtualenv with interpreter /usr/bin/python2
dh_auto_build: virtualenv --always-copy --clear /«PKGBUILDDIR»/build/usr/lib/mycroft-core returned exit code 1
	cd /«PKGBUILDDIR»
debian/rules:10: recipe for target 'build-arch' failed
make: *** [build-arch] Error 25
dpkg-buildpackage: error: debian/rules build-arch gave error exit status 2

```

**Comment by jhermann** [comment] 2016-09-08 10:13
Usually caused by your PyPI repo being down. Not really a dh-venv problem.

**Comment by nailor** [comment] 2016-09-12 12:17
Since it indeed looks like an external issue, I'm closing this ticket. Thanks @jhermann for a reply!

**Closed by nailor** 2016-09-12 12:17 UTC
