### ISSUE TITLE
Trouble building Numpy with dh-virtualenv

### ISSUE THREAD

**Issue by brifordwylie** [spotify/dh-virtualenv#85] opened 2015-04-01 02:40 UTC
Disclaimer: My Debian Package knowledge is super weak. 

Context: I can do the following:
     $ sudo pip install numpy (on the system python)
     $ pip install numpy (on a new blank virtualenv)

But I cannot get numpy to build within dh-virualenv

Version: git clone (3-31-15)
Machine: 14.04 Ubuntu (trusty)

Replication: 
1) Follow the instructions here http://dh-virtualenv.readthedocs.org/en/latest/tutorial.html
2) put 'numpy' in the requirements.txt file
3) dpkg-buildpackage -us -uc

Error:
```
/usr/bin/gfortran -Wall -g -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/numpy/linalg/lapack_litemodule.o build/temp.linux-x86_64-2.7/numpy/linalg/lapack_lite/python_xerbla.o -L/usr/lib/atlas-base/atlas -L/usr/lib/atlas-base -Lbuild/temp.linux-x86_64-2.7 -llapack -lf77blas -lcblas -latlas -lgfortran -o build/lib.linux-x86_64-2.7/numpy/linalg/lapack_lite.so
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 0 has invalid symbol index 11
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 1 has invalid symbol index 12
...
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
```

So I noticed that the FLAGS to gfortran were different, the first two that worked had these flags
```
/usr/bin/gfortran -Wall -g -Wall -g -shared 
 build/temp.linux-x86_64-2.7/numpy/linalg/lapack_litemodule.o 
 build/temp.linux-x86_64-2.7/numpy/linalg/lapack_lite/python_xerbla.o 
 -L/usr/lib/atlas-base/atlas 
 -L/usr/lib/atlas-base -Lbuild/temp.linux-x86_64-2.7 
 -llapack -lf77blas -lcblas -latlas -lgfortran 
 -o build/lib.linux-x86_64-2.7/numpy/linalg/lapack_lite.so
```

The dh-virtualenv version had different FLAGS
```
 /usr/bin/gfortran -Wall -g -Wl,-Bsymbolic-functions -Wl,-z,relro 
 build/temp.linux-x86_64-2.7/numpy/linalg/lapack_litemodule.o
 build/temp.linux-x86_64-2.7/numpy/linalg/lapack_lite/python_xerbla.o 
 -L/usr/lib/atlas-base/atlas 
 -L/usr/lib/atlas-base 
 -Lbuild/temp.linux-x86_64-2.7 
 -llapack -lf77blas -lcblas -latlas -lgfortran 
 -o build/lib.linux-x86_64-2.7/numpy/linalg/lapack_lite.so
```

Any suggestions are greatly appreciated :)

**Comment by benjaminirving** [comment] 2015-06-03 18:05
I had a similar issue installing scikit-learn with dh-virtualenv

It worked fine when running
`pip install scikit-learn in a virtualenv`

But also gave a gfortran error when installing with dh-virtualenv

Once I had install libatlas-base-dev it seemed to work fine:
`sudo apt-get install libatlas-base-dev`

I assume this is because of the extra flags

I also have the libraries libblas-dev, liblapack-dev and python-all-dev installed

**Comment by jooon** [comment] 2015-07-02 14:06
I have seen the same issue. I worked around it by adding:

LDFLAGS += -shared

to the top of debian/rules.

The debian build process in Ubuntu sets some compiler flags, like LDFLAGS because they want all code to be built with some build hardening flags for security. In the numpy build, gcc links with -shared flag regardless of LDFLAGS, but gfortran drops -shared if LDFLAGS is set.

I am not sure where the bug is, but it doesn't feel like this is a dh-virtualenv bug.

**Comment by nailor** [comment] 2015-07-03 09:29
Let me know if what @jooon recommended fixes your issue! I'm closing this bug for now and feel free to reopen it in case you still feel the problem is in the dh-virtualenv!

**Closed by nailor** 2015-07-03 09:29 UTC

**Comment by jooon** [comment] 2015-07-30 15:27
I want to add some additional information to this thread for future reference even though it is closed.

After successfully building numpy with LDFLAGS += -shared, I got a different problem when I tried to build scipy. To fix that problem I added FFLAGS += -fPIC. However, then I got another problem when I couldn't build gevent. The configure script failed even because the minimal conftest segfaulted when I built with build-hardening flags and LDFLAGS += -shared.

Instead I tried to remove all flags and managed to build numpy 1.9.2, scipy 0.16.0 and gevent 1.0.2 in the same dh-virtualenv with these make commands in debian/rules:

unexport LDFLAGS
unexport FFLAGS

**Comment by joostdevries** [comment] 2015-08-07 09:04
@jooon :+1: :+1: :+1: :+1:  thanks for posting that, exactly what I needed.

**Comment by markabey** [comment] 2016-12-22 12:05
Even with unexporting LDFLAGS and FFLAGS, numpy wouldn't build for me until I used setuptools

```
override_dh_virtualenv:
	dh_virtualenv --setuptools
```

**Comment by mdcroce** [comment] 2017-03-16 17:13
@jooon  @brifordwylie, can you please provide your debian rules to install a project that has numpy? I'm still getting this error:

```
error: Command "/usr/bin/gfortran -Wall -g -Wl,-Bsymbolic-functions -Wl,-z,relro 
build/temp.linux-x86_64-2.7/numpy/linalg/lapack_litemodule.o
build/temp.linux-x86_64-2.7/numpy/linalg/lapack_lite/python_xerbla.o 
-L/usr/lib/atlas-base/atlas -L/usr/lib/atlas-base -Lbuild/temp.linux-x86_64-2.7
-llapack -lf77blas -lcblas -latlas -lf77blas -lcblas
-lgfortran -o build/lib.linux-x86_64-2.7/numpy/linalg/lapack_lite.so" failed with exit status 1
error
```
