### ISSUE TITLE
Packages installed with -e are badly installed

### ISSUE THREAD

**Issue by bochecha** [spotify/dh-virtualenv#200] opened 2017-02-24 14:27 UTC
At Ideascube, we use dh-virtualenv to build our Debian package.

Some of our dependencies are specified in our `requirements.txt` file with e.g:

```
-e git+https://github.com/ideascube/django-select-multiple-field@remove-dj110-warning#egg=django-select-multiple-field
```

We just built a package, and it contains the file:

```
$ cat /opt/venvs/ideascube/lib/python3.4/site-packages/django-select-multiple-field.egg-link
/build/ideascube-Ls3MlA/ideascube-0.21.1/debian/ideascube/opt/venvs/ideascube/src/django-select-multiple-field
```

That's clearly the wrong path!

Of course, it's kind of obvious that this is the path which ends up in the `.egg-link` file, since that's the install root passed to pip.

However, dh-virtualenv should probably make a pass on all the `*.egg-link` files at the end of the build process and fix the paths.

**Comment by bochecha** [comment] 2017-02-24 15:09
Oops, sorry, this shouldn't have been fixed.

**Comment by jhermann** [comment] 2018-09-28 10:34
Dupe of #134 ⇒ close.

**Closed** 2018-09-30 18:59 UTC
Labels: duplicate
